// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvedawllemtyfkxeenll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2ZWRhd2xsZW10eWZreGVlbmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzY4NzUsImV4cCI6MjA3NDIxMjg3NX0._JXEftIIgYnv4_wD2cZ4PLP1kYfOy9XHx762eQni_Ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});